//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverwatchNightlyUpdaterClient.UpdateSerive {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateSerive.IUpdateService")]
    public interface IUpdateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/UpdateLatestCompetitiveStat", ReplyAction="http://tempuri.org/IUpdateService/UpdateLatestCompetitiveStatResponse")]
        void UpdateLatestCompetitiveStat(string userName, int platformId, int regionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/UpdateLatestCompetitiveStat", ReplyAction="http://tempuri.org/IUpdateService/UpdateLatestCompetitiveStatResponse")]
        System.Threading.Tasks.Task UpdateLatestCompetitiveStatAsync(string userName, int platformId, int regionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateServiceChannel : OverwatchNightlyUpdaterClient.UpdateSerive.IUpdateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateServiceClient : System.ServiceModel.ClientBase<OverwatchNightlyUpdaterClient.UpdateSerive.IUpdateService>, OverwatchNightlyUpdaterClient.UpdateSerive.IUpdateService {
        
        public UpdateServiceClient() {
        }
        
        public UpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateLatestCompetitiveStat(string userName, int platformId, int regionId) {
            base.Channel.UpdateLatestCompetitiveStat(userName, platformId, regionId);
        }
        
        public System.Threading.Tasks.Task UpdateLatestCompetitiveStatAsync(string userName, int platformId, int regionId) {
            return base.Channel.UpdateLatestCompetitiveStatAsync(userName, platformId, regionId);
        }
    }
}
