//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverwatchStats.WCF.Test.CombatService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CombatService.ICombatService")]
    public interface ICombatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICombatService/GetLatestCompetitiveCombatStats", ReplyAction="http://tempuri.org/ICombatService/GetLatestCompetitiveCombatStatsResponse")]
        OverwatchStats.Common.Data.General.OverallCombat GetLatestCompetitiveCombatStats(System.Guid profileGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICombatService/GetLatestCompetitiveCombatStats", ReplyAction="http://tempuri.org/ICombatService/GetLatestCompetitiveCombatStatsResponse")]
        System.Threading.Tasks.Task<OverwatchStats.Common.Data.General.OverallCombat> GetLatestCompetitiveCombatStatsAsync(System.Guid profileGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICombatService/GetAllCompetitiveCombatStats", ReplyAction="http://tempuri.org/ICombatService/GetAllCompetitiveCombatStatsResponse")]
        OverwatchStats.Common.Data.General.OverallCombat[] GetAllCompetitiveCombatStats(System.Guid profileGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICombatService/GetAllCompetitiveCombatStats", ReplyAction="http://tempuri.org/ICombatService/GetAllCompetitiveCombatStatsResponse")]
        System.Threading.Tasks.Task<OverwatchStats.Common.Data.General.OverallCombat[]> GetAllCompetitiveCombatStatsAsync(System.Guid profileGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICombatServiceChannel : OverwatchStats.WCF.Test.CombatService.ICombatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CombatServiceClient : System.ServiceModel.ClientBase<OverwatchStats.WCF.Test.CombatService.ICombatService>, OverwatchStats.WCF.Test.CombatService.ICombatService {
        
        public CombatServiceClient() {
        }
        
        public CombatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CombatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CombatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CombatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OverwatchStats.Common.Data.General.OverallCombat GetLatestCompetitiveCombatStats(System.Guid profileGuid) {
            return base.Channel.GetLatestCompetitiveCombatStats(profileGuid);
        }
        
        public System.Threading.Tasks.Task<OverwatchStats.Common.Data.General.OverallCombat> GetLatestCompetitiveCombatStatsAsync(System.Guid profileGuid) {
            return base.Channel.GetLatestCompetitiveCombatStatsAsync(profileGuid);
        }
        
        public OverwatchStats.Common.Data.General.OverallCombat[] GetAllCompetitiveCombatStats(System.Guid profileGuid) {
            return base.Channel.GetAllCompetitiveCombatStats(profileGuid);
        }
        
        public System.Threading.Tasks.Task<OverwatchStats.Common.Data.General.OverallCombat[]> GetAllCompetitiveCombatStatsAsync(System.Guid profileGuid) {
            return base.Channel.GetAllCompetitiveCombatStatsAsync(profileGuid);
        }
    }
}
